### ISSUE TITLE
spawn_block function should ignore snow

### ISSUE THREAD

**Issue by tacotexmex** [taikedz-mt/rspawn#2]
When placing spawn_block, snow should probably be removed and the node replace the node beneath it.

![screenshot_20190205_044140](https://user-images.githubusercontent.com/25328789/52252094-b8e0f480-2900-11e9-8f9b-3eebf3575416.png)

**Comment by taikedz** [comment]
Good observation. In fact, I could apply this to any `falling_node`? Snow is one type, but maybe flora as well should be affected? Trickier with sand... I'll have to think about that one...

**Comment by tacotexmex** [comment]
Sand is okay imo. Just make it look for normal drawtype and remove any nodebox or plantlikes above?

**Comment by taikedz** [comment]
@tacotexmex Apologies for the delay. Want to give this a try ?

**Comment by taikedz** [comment]
Merged in 4a643af
