### ISSUE TITLE
low performance and mem exausted with huge server users database

### ISSUE THREAD

**Issue by mckaygerhard** [taikedz-mt/rspawn#6]
i installed the mod, start a server and everythinhg is fine.. before anything the hardware are 8 cores xeon, 8G RAM and SSD disk, remove AWS server with debian 9 powered, at subs.fusilsystem.com (yes is the sub nasa no rulez server, only for braves)

finally after months of use we **had to remove this mod because a poor behaviour performance**.. After a while:

1.  if the area is small, spawn points is exhausted to find free points in the area, cos now the user database is too huge, around a 1G text file (yes i am one of the VenenuX sub-nasa admins)..
2.  for a new spawn point, and if it is very large the spawn area, server is unable to handle the memory for the lua engine, so get a mem exausted

configuration:

```
rspawn.debug = true
rspawn.spawn_anywhere = false
rspawn.kick_on_fail = false
rspawn.max_pregen = 30
rspawn.search_radius = 96
rspawn.gen_frequency = 400
rspawn.exile_distance = 100
rspawn.cooldown_time = 400
rspawn.min_x = -400
rspawn.max_x = 400
rspawn.min_z = -400
rspawn.max_z = 400
```

This is the constant error (disappears after removing mod):
```
Oct  8 09:37:53 venenux-server minetestserver: 2021-10-08 09:37:53: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: OOM error from mod '' in callback createAuth(): not enough memory
```

This is the log error if i try to enhanced the spawn area size to 800 ratio:

```
Oct 10 17:53:39 venenux-server minetestserver: 2021-10-10 17:53:39: [Server]: [rspawn] DEBUG : Trying somewhere around (0,0,0)
Oct 10 17:53:39 venenux-server minetestserver: 2021-10-10 17:53:39: [Server]: [rspawn] DEBUG : Searching (-96,0,-96) to (96,192,96)
Oct 10 17:53:39 venenux-server minetestserver: 2021-10-10 17:53:39: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'rspawn' in callback environment_Step(): ...ib/games/minetest/games/venenux/mods/rspawn/init.lua:74: find_nodes_in_area(): area volume exceeds allowed value of 4096000
Oct 10 17:53:39 venenux-server minetestserver: 2021-10-10 17:53:39: ERROR[Main]: stack traceback:
Oct 10 17:53:39 venenux-server minetestserver: 2021-10-10 17:53:39: ERROR[Main]: #011[C]: in function 'find_nodes_in_area'
Oct 10 17:53:39 venenux-server minetestserver: 2021-10-10 17:53:39: ERROR[Main]: #011...ib/games/minetest4/games/venenux/mods/rspawn/init.lua:74: in function 'newspawn'
Oct 10 17:53:39 venenux-server minetestserver: 2021-10-10 17:53:39: ERROR[Main]: #011...minetest4/games/venenux/mods/rspawn/lua/pregeneration.lua:33: in function 'func'
Oct 10 17:53:39 venenux-server minetestserver: 2021-10-10 17:53:39: ERROR[Main]: #011/usr/share/minetest4/builtin/common/after.lua:18: in function </usr/share/minetes4t/builtin/common/after.lua:4>
Oct 10 17:53:39 venenux-server minetestserver: 2021-10-10 17:53:39: ERROR[Main]: #011/usr/share/minetest4/builtin/game/register.lua:420: in function </usr/share/minetest4/builtin/game/register.lua:400>
Oct 10 17:53:39 venenux-server minetestserver: 2021-10-10 17:53:39: ERROR[Main]: stack traceback:
Oct 10 17:57:30 venenux-server minetestserver: 2021-10-10 17:57:30: [Main]: Automatically selecting world at [/var/lib/games/minetest/worlds/venenuxharcore]
```

of course the excees value of area is cos we try to enhanced the size of the area.. but the mod does not take in consideration that when minetest uses database for auth, still there are a txt files that defines old map and auth, so setting still are cached or something i dont known

**after removes the mod there's no more crash of server around memory exausted**, we will start a new mod for random spawn that just makes a random point and no more crap of features..  (my proposal is that this mod just depends on that, meanwhile i code https://codeberg.org/minenux/spawnrand that only land randown spawn at login)

**Comment by mckaygerhard** [comment]
the offending code is on `set_newplayer_spawn`,  due spawn pouint exaustion 

the function evaluates if there are positions .. or if it already has .. it searches again .. and since it does not find it is called again but it returns to the same vicious circle because there is no point available .. it continues to call until the memory stack breaks and the server bursts .. this only happens in serious servers with many users like mine from venenux .. more than a million users ..  thanks to @darltrash for some hints about code uglyfy XD :laughing: 

```

    if not rspawn.playerspawns[playername] then
        local newpos = rspawn:get_next_spawn()
-- the function evaluates if there are positions
        if newpos then
            rspawn:set_player_spawn(playername, newpos)
---  or if it already has .. 
        else
            -- We did not get a new position
-- try to kick the palyer (easy solution) but if is not a mandate . musta search again:
            if rspawn.kick_on_fail then
               	minetest.kick_player(playername, "No personalized spawn points available - please try again later.")
            else
               	minetest.chat_send_player(playername, "Could not get custom spawn! Retrying in "..rspawn.gen_frequency..$
               	minetest.chat_send_player(rspawn.admin, "Exhausted spawns! Could not spawn "..playername)
                minetest.log("warning", "rspawn -- Exhausted spawns! Could not spawn "..playername)
-- HERE THE OFENDING PART: WE MUST CHANGE IF THERE's NO NEW SPAWN just get back again to
                minetest.after(rspawn.gen_frequency, function()
-- called again but it returns to the same vicious circle because there is no point available ..
                    rspawn:set_newplayer_spawn(player)
--  it continues to call until the memory stack breaks and the server bursts ..
                end)
            end
        end
    end

```

i made a new mod .. more simpler.. this mod just generates the positions and call my mod.. is more easy o change the funtion.. 

this is a bad code.. minetest 5 is a shit cos doesn not handle this kind of waste of resources errors, MT 0.4 give me the hints..

**Comment by taikedz** [comment]
Yes, I didn't code this expecting millions of players. I ran a server with this fine on lower spec, but if you have high numbers of users, then it will have huge performance problems

I'd need to re-write this to use a database plugin for it to be scalable.

Also that item where you found an offending location - yes, that will deifinitely break your server if you have super-super high numbers of players. In fact, I should have been maintaining a table of appropriate locations, and registering through there, rather than randomly picking a spot and searching it. Again, not coded for scalability, and would need a database connection to be performant.

If you have a better solution, I'd love to see it. If it can scale and takes care of corner cases (like, not spawning a player into a dark cave, or into a wall 😆) then even better, and you mod would be more useful by then than mine.

EDIT: I am no longer active on Minetest. No idea when I will be able to return to it.

**Comment by mckaygerhard** [comment]
maybe you can use the randow_spawn logic of https://github.com/NathanSalapat/random_spawn/issues/1 i started that discussion for.. and integrate it.. i checked that we can made that:

1. an option only for random spawn.. to large servers.. you can set a variable that when active, dissable all the resto features, like invite spawn point towns, and respawn poits
2. change the logic of the randow spawn to the hathan ones

**Comment by mckaygerhard** [comment]
i not used the `minetest.register_on_joinplayer` yet cos for already set beds of players will need a better logic so i used `minetest.register_on_newplayer` ... https://codeberg.org/minenux/spawnrand/commit/2b50e329f0ee339090de76146ee6b440ab53527b  later i will fork this mod to only use the `/newspawn` logic only.. adn i will request your help at https://codeberg.org/minenux/spawnnew

**Comment by mckaygerhard** [comment]
hi .. after reading the #9 merge comment by you @taikedz  i noted the recursive callback at https://github.com/taikedz-mt/rspawn/blob/60795a69e54ae254f7751727a819eb891d831ef9/lua/pregeneration.lua#L39 maybe we just can set the spawn point to the lasted generated.. and if are a new player just let in the designed falback spawn point? of course by enabling a setting flags like "rspawn.safe_procedure" and if enabled we just don't try to indefinitely find spawn points

sounds nasty but i try to fix this performance issue around `rspawn.playerspawns` and `push_new_spawn`

**Comment by taikedz** [comment]
Yeah... the recursive call in `rspawn:set_newplayer_spawn()` was never an issue for me, but if your server has pretty much explored a heavy amount of the map already, a lot of the randomized spawn attempts are in fact going to cause deep, deep recursion... and blow the stack.

> maybe we just can set the spawn point to the lasted generated.. 

That's what the spawn pre-gen is meant to provide - if a new player joins, the mod first checks if there are any pre-generated ones, and assigns that one to the player.

It only *actually* searches for new spawns if there is no stock of pre-generated spawns.

As a solution, we essentially need a counter, [which I have now done](https://github.com/taikedz-mt/rspawn/commit/f666465cdfec5dfb33d0e6e028ef1d8362cb8edf).

**Comment by taikedz** [comment]
There is no recursive call at the line you specified though? It's just a send-chat-message?

**Comment by mckaygerhard** [comment]
so thanks.. i guess i'll close this via https://github.com/taikedz-mt/rspawn/commit/f666465cdfec5dfb33d0e6e028ef1d8362cb8edf thanks for your work.. i'll test this on my huge production server at venenux subs.fusilsystem.com and later report feedback cos as i can see.. this may solve in mayor way the performance issue

**Comment by mckaygerhard** [comment]
umm it looks better now.. in the graps.. the most peaks are when i was using rspawn, later disabled.. i enabled just today and it seems works with more than 20 users concurrently and a million of registered users in auth.txt on minetest 0.4.17 version
![imagen](https://user-images.githubusercontent.com/1571724/138488763-7a377825-6f6a-4cfa-abd4-9d94e376707b.png)

when there's no more pregen my character does not teleport to new spawn.. as must be.. cos `newspawn` command only set new spawn point.. so if i killme 

after a quick fix that seems unrelated (i'll open new issue) i got this log:
```

Oct 22 11:44:13 venenux minetestserver: 2021-10-22 11:44:13: WARNING[Server]: rspawn -- Could not find spawn point for user1
Oct 22 11:44:13 venenux minetestserver: 2021-10-22 11:44:13: ACTION[Server]: user1 respawns at (-5,14,-141)
Oct 22 11:44:18 venenux minetestserver: 2021-10-22 11:44:18: [Server]: [rspawn] DEBUG : Trying somewhere around (-122,1,-126)
Oct 22 11:44:18 venenux minetestserver: 2021-10-22 11:44:18: [Server]: [rspawn] DEBUG : Searching (-186,1,-190) to (-58,65,-62)
Oct 22 11:44:18 venenux minetestserver: 2021-10-22 11:44:18: [Server]: [rspawn] DEBUG : Found 137857 air nodes within 64
Oct 22 11:44:18 venenux minetestserver: 2021-10-22 11:44:18: [Server]: [rspawn] DEBUG : Generated (-78,18,-135)
Oct 22 11:44:18 venenux minetestserver: 2021-10-22 11:44:18: [Server]: Wrote rspawn data with 1 pregen nodes
Oct 22 11:44:18 venenux minetestserver: 2021-10-22 11:44:18: [Server]: [rspawn] DEBUG : Freeing forceloaded blocks ____/ :: {
Oct 22 11:44:18 venenux minetestserver: pos1 = "(-186,1,-190)",
Oct 22 11:44:18 venenux minetestserver: pos2 = "(-58,65,-62)"
Oct 22 11:44:18 venenux minetestserver: }
```

**of course i can close this cos performance is better now.. new players ramdownly respawn until a new spawn point is set with bed or by `/newspawn` command** i setup a similar server "cloud-server4" and seems working better:

![imagen](https://user-images.githubusercontent.com/1571724/138494373-95f2b9c7-4cad-490e-974c-65eec6ff58ed.png)
